[mgr]
show_hidden = false
linemode = "mtime"
sort_by      = "mtime"     # "name", "size", "mtime", "extension" gibi
sort_sensitive = false     # Büyük/küçük harf duyarlılığı
sort_reverse   = true      # Büyükten küçüğe (descending) için true
sort_dir_first = true      # Klasörleri her zaman en üstte göster

name = "name"
display = "name"

[[mgr.append_columns]]
name = "mtime"
display = "mtime"
format = "%Y-%m-%d %H:%M"  # Tarih formatı (Yıl-Ay-Gün Saat:Dakika)

[[mgr.append_columns]]
name = "size"
display = "size"

